
## zsh shell config ("~/.zshrc")
plugins=(
  git
  zsh-autosuggestions
  zsh-syntax-highlighting

  )

source $ZSH/oh-my-zsh.sh
eval "$(starship init zsh)"
eval "$(zoxide init zsh)"

DISABLE_UPDATE_PROMPT=true      # No update nagging
zstyle ':omz:update' mode disabled
zstyle ':vcs_info:*' enable false   # Disable heavy Git info checks

ZSH_THEME="powerlevel10k/powerlevel10k"

alias la='eza -l -a --icons --no-permissions --no-user --no-time --group-directories-first'
alias ls='eza -1 --icons --group-directories-first'

alias ubuntu='proot-distro login ubuntu'
alias bat='bat -P --style=header,grid'
alias py='python'
alias zi='zoxide query -l | fzf --height 40% --reverse --preview 'ls -la {}' | xargs -r z'

setopt HIST_IGNORE_ALL_DUPS SHARE_HISTORY #same zsh history in multiple terminal 
setopt CORRECT #For correction of mistyped command
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'


bindkey '^[[A' history-beginning-search-backward
bindkey '^[[B' history-beginning-search-forward

# 256 colors allowing
export TERM=xterm-256color
export COLORTERM=truecolor

export HOST='username' # root@localhost -> root@username
