
## zsh shell config ("~/.zshrc")

ZSH_THEME="powerlevel10k/powerlevel10k"
alias ls='eza -1 --icons --group-directories-first'


setopt HIST_IGNORE_ALL_DUPS SHARE_HISTORY #same zsh history in mul
tiple te>
setopt CORRECT #For correction of mistyped command
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'


bindkey '^[[A' history-beginning-search-backward
bindkey '^[[B' history-beginning-search-forward

# 256 colors allowing
export TERM=xterm-256color
export COLORTERM=truecolor

export HOST='username' # root@localhost -> root@username
